"""Curated static registry of current AI models across major providers.

Model IDs are the exact strings passed to the `model=` parameter in API calls.
Pricing is in USD per 1 million tokens. Data verified against official docs
as of February 2026.
"""

MODELS = {
    # ─── OpenAI: Current ───────────────────────────────────────────────
    "gpt-5.2": {
        "id": "gpt-5.2",
        "display_name": "GPT-5.2",
        "provider": "OpenAI",
        "context_window": 400_000,
        "max_output_tokens": 128_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.75,
        "pricing_output": 14.00,
        "knowledge_cutoff": "2025-08",
        "release_date": "2025-12",
        "status": "current",
        "notes": "Latest flagship GPT model with thinking, 400K context",
    },
    "gpt-5": {
        "id": "gpt-5",
        "display_name": "GPT-5",
        "provider": "OpenAI",
        "context_window": 400_000,
        "max_output_tokens": 128_000,
        "vision": True,
        "reasoning": False,
        "pricing_input": 1.25,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2025-06",
        "release_date": "2025-08",
        "status": "current",
        "notes": "400K context, general-purpose flagship",
    },
    "gpt-5-mini": {
        "id": "gpt-5-mini",
        "display_name": "GPT-5 Mini",
        "provider": "OpenAI",
        "context_window": 400_000,
        "max_output_tokens": 128_000,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.25,
        "pricing_output": 2.00,
        "knowledge_cutoff": "2025-06",
        "release_date": "2025-09",
        "status": "current",
        "notes": "Cost-efficient GPT-5 variant, 400K context",
    },
    "gpt-4.1": {
        "id": "gpt-4.1",
        "display_name": "GPT-4.1",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 2.00,
        "pricing_output": 8.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "1M context window, strong coding and instruction following",
    },
    "gpt-4.1-mini": {
        "id": "gpt-4.1-mini",
        "display_name": "GPT-4.1 Mini",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.40,
        "pricing_output": 1.60,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "1M context, cost-efficient",
    },
    "gpt-4.1-nano": {
        "id": "gpt-4.1-nano",
        "display_name": "GPT-4.1 Nano",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Fastest and cheapest GPT-4.1 variant",
    },
    "o3": {
        "id": "o3",
        "display_name": "o3",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 2.00,
        "pricing_output": 8.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Flagship reasoning model, strong at math/science/coding",
    },
    "o4-mini": {
        "id": "o4-mini",
        "display_name": "o4-mini",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.10,
        "pricing_output": 4.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Cost-efficient reasoning model",
    },
    "o3-mini": {
        "id": "o3-mini",
        "display_name": "o3-mini",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": False,
        "reasoning": True,
        "pricing_input": 1.10,
        "pricing_output": 4.40,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-01",
        "status": "current",
        "notes": "Predecessor to o4-mini, still available",
    },
    # ─── OpenAI: Legacy/Deprecated ─────────────────────────────────────
    "gpt-4o": {
        "id": "gpt-4o",
        "display_name": "GPT-4o",
        "provider": "OpenAI",
        "context_window": 128_000,
        "max_output_tokens": 16_384,
        "vision": True,
        "reasoning": False,
        "pricing_input": 2.50,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2024-10",
        "release_date": "2024-05",
        "status": "legacy",
        "notes": "Superseded by GPT-4.1 and GPT-5 series",
    },
    "gpt-4o-mini": {
        "id": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "provider": "OpenAI",
        "context_window": 128_000,
        "max_output_tokens": 16_384,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.15,
        "pricing_output": 0.60,
        "knowledge_cutoff": "2024-10",
        "release_date": "2024-07",
        "status": "deprecated",
        "notes": "Superseded by GPT-4.1 Mini/Nano",
    },
    # ─── Anthropic: Current ────────────────────────────────────────────
    "claude-opus-4-6": {
        "id": "claude-opus-4-6",
        "display_name": "Claude Opus 4.6",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 128_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 5.00,
        "pricing_output": 25.00,
        "knowledge_cutoff": "2025-05",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Most capable Anthropic model, extended thinking, adaptive thinking",
    },
    "claude-sonnet-4-5-20250929": {
        "id": "claude-sonnet-4-5-20250929",
        "display_name": "Claude Sonnet 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 64_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-09",
        "status": "current",
        "notes": "Best speed/intelligence balance, extended thinking. Alias: claude-sonnet-4-5",
    },
    "claude-haiku-4-5-20251001": {
        "id": "claude-haiku-4-5-20251001",
        "display_name": "Claude Haiku 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 64_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.00,
        "pricing_output": 5.00,
        "knowledge_cutoff": "2025-02",
        "release_date": "2025-10",
        "status": "current",
        "notes": "Fastest Anthropic model, extended thinking. Alias: claude-haiku-4-5",
    },
    # ─── Anthropic: Legacy/Deprecated ──────────────────────────────────
    "claude-opus-4-5": {
        "id": "claude-opus-4-5",
        "display_name": "Claude Opus 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 64_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 5.00,
        "pricing_output": 25.00,
        "knowledge_cutoff": "2025-05",
        "release_date": "2025-11",
        "status": "legacy",
        "notes": "Superseded by Claude Opus 4.6. Full ID: claude-opus-4-5-20251101",
    },
    "claude-opus-4-1": {
        "id": "claude-opus-4-1",
        "display_name": "Claude Opus 4.1",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 32_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 15.00,
        "pricing_output": 75.00,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-08",
        "status": "legacy",
        "notes": "Superseded by Claude Opus 4.5/4.6. Full ID: claude-opus-4-1-20250805",
    },
    "claude-sonnet-4-0": {
        "id": "claude-sonnet-4-0",
        "display_name": "Claude Sonnet 4.0",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 64_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-05",
        "status": "legacy",
        "notes": "Superseded by Claude Sonnet 4.5. Full ID: claude-sonnet-4-20250514",
    },
    "claude-3-7-sonnet-20250219": {
        "id": "claude-3-7-sonnet-20250219",
        "display_name": "Claude 3.7 Sonnet",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 64_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2024-10",
        "release_date": "2025-02",
        "status": "deprecated",
        "notes": "Superseded by Claude Sonnet 4.x. Alias: claude-3-7-sonnet-latest",
    },
    "claude-opus-4-0": {
        "id": "claude-opus-4-0",
        "display_name": "Claude Opus 4.0",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 32_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 15.00,
        "pricing_output": 75.00,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-05",
        "status": "legacy",
        "notes": "Superseded by Claude Opus 4.5/4.6. Full ID: claude-opus-4-20250514",
    },
    # ─── Google: Current ───────────────────────────────────────────────
    "gemini-3-pro-preview": {
        "id": "gemini-3-pro-preview",
        "display_name": "Gemini 3 Pro (Preview)",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 2.00,
        "pricing_output": 12.00,
        "knowledge_cutoff": "2025-09",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Latest Gemini flagship, 1M context, preview",
    },
    "gemini-3-flash-preview": {
        "id": "gemini-3-flash-preview",
        "display_name": "Gemini 3 Flash (Preview)",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 0.50,
        "pricing_output": 3.00,
        "knowledge_cutoff": "2025-09",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Fast Gemini 3 variant, preview",
    },
    "gemini-2.5-pro": {
        "id": "gemini-2.5-pro",
        "display_name": "Gemini 2.5 Pro",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.25,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-03",
        "status": "current",
        "notes": "Thinking model, 1M context",
    },
    "gemini-2.5-flash": {
        "id": "gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 0.30,
        "pricing_output": 2.50,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-05",
        "status": "current",
        "notes": "Fast and cost-efficient with thinking",
    },
    "gemini-2.5-flash-lite": {
        "id": "gemini-2.5-flash-lite",
        "display_name": "Gemini 2.5 Flash Lite",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-06",
        "status": "current",
        "notes": "Cheapest Gemini option, no thinking mode",
    },
    # ─── Google: Legacy/Deprecated ─────────────────────────────────────
    "gemini-2.0-flash": {
        "id": "gemini-2.0-flash",
        "display_name": "Gemini 2.0 Flash",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2024-08",
        "release_date": "2025-02",
        "status": "deprecated",
        "notes": "Retiring March 2026, use Gemini 2.5 Flash instead",
    },
    # ─── xAI: Current ────────────────────────────────────────────────
    "grok-4": {
        "id": "grok-4",
        "display_name": "Grok 4",
        "provider": "xAI",
        "context_window": 256_000,
        "max_output_tokens": 131_072,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2024-11",
        "release_date": "2025-07",
        "status": "current",
        "notes": "xAI flagship reasoning model",
    },
    "grok-4.1-fast": {
        "id": "grok-4.1-fast",
        "display_name": "Grok 4.1 Fast",
        "provider": "xAI",
        "context_window": 2_000_000,
        "max_output_tokens": 131_072,
        "vision": True,
        "reasoning": True,
        "pricing_input": 0.20,
        "pricing_output": 0.50,
        "knowledge_cutoff": "2024-11",
        "release_date": "2025-11",
        "status": "current",
        "notes": "2M context, fast tool-calling model, low hallucination",
    },
    # ─── xAI: Legacy ─────────────────────────────────────────────────
    "grok-3": {
        "id": "grok-3",
        "display_name": "Grok 3",
        "provider": "xAI",
        "context_window": 131_072,
        "max_output_tokens": 131_072,
        "vision": True,
        "reasoning": False,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2024-11",
        "release_date": "2025-02",
        "status": "legacy",
        "notes": "Superseded by Grok 4 series",
    },
    "grok-3-mini": {
        "id": "grok-3-mini",
        "display_name": "Grok 3 Mini",
        "provider": "xAI",
        "context_window": 131_072,
        "max_output_tokens": 131_072,
        "vision": False,
        "reasoning": True,
        "pricing_input": 0.30,
        "pricing_output": 0.50,
        "knowledge_cutoff": "2024-11",
        "release_date": "2025-02",
        "status": "legacy",
        "notes": "Compact reasoning model, superseded by Grok 4.1 Fast",
    },
    # ─── Meta: Current ────────────────────────────────────────────────
    # Note: Meta does not have a direct commercial API. These models are
    # open-weight and accessed via third-party providers (Together AI,
    # Fireworks, Groq, etc.). IDs and pricing vary by provider.
    # Pricing below reflects typical third-party API rates.
    "llama-4-maverick": {
        "id": "llama-4-maverick",
        "display_name": "Llama 4 Maverick",
        "provider": "Meta",
        "context_window": 1_048_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.20,
        "pricing_output": 0.60,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Open-weight MoE, no direct Meta API, access via Together/Fireworks/Groq",
    },
    "llama-4-scout": {
        "id": "llama-4-scout",
        "display_name": "Llama 4 Scout",
        "provider": "Meta",
        "context_window": 10_000_000,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.15,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Open-weight, 10M context, no direct Meta API, access via third-party providers",
    },
    # ─── Meta: Legacy ─────────────────────────────────────────────────
    "llama-3.3-70b": {
        "id": "llama-3.3-70b",
        "display_name": "Llama 3.3 70B",
        "provider": "Meta",
        "context_window": 128_000,
        "max_output_tokens": 4_096,
        "vision": False,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.30,
        "knowledge_cutoff": "2024-12",
        "release_date": "2024-12",
        "status": "legacy",
        "notes": "Superseded by Llama 4 series, access via third-party providers",
    },
    # ─── Mistral: Current ─────────────────────────────────────────────
    "mistral-large-3-25-12": {
        "id": "mistral-large-3-25-12",
        "display_name": "Mistral Large 3",
        "provider": "Mistral",
        "context_window": 256_000,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.50,
        "pricing_output": 1.50,
        "knowledge_cutoff": "2025-11",
        "release_date": "2025-12",
        "status": "current",
        "notes": "MoE 675B flagship, strong multilingual, Apache 2.0",
    },
    "mistral-small-2506": {
        "id": "mistral-small-2506",
        "display_name": "Mistral Small 3.2",
        "provider": "Mistral",
        "context_window": 128_000,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.30,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-06",
        "status": "current",
        "notes": "Fast and cost-efficient, open-weight",
    },
    "devstral-2-25-12": {
        "id": "devstral-2-25-12",
        "display_name": "Devstral 2",
        "provider": "Mistral",
        "context_window": 256_000,
        "max_output_tokens": 8_192,
        "vision": False,
        "reasoning": False,
        "pricing_input": 0.05,
        "pricing_output": 0.22,
        "knowledge_cutoff": "2025-11",
        "release_date": "2025-12",
        "status": "current",
        "notes": "Specialized coding agent model, open-weight",
    },
    # ─── Mistral: Legacy ──────────────────────────────────────────────
    "codestral-2508": {
        "id": "codestral-2508",
        "display_name": "Codestral",
        "provider": "Mistral",
        "context_window": 256_000,
        "max_output_tokens": 8_192,
        "vision": False,
        "reasoning": False,
        "pricing_input": 0.30,
        "pricing_output": 0.90,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-08",
        "status": "legacy",
        "notes": "Superseded by Devstral 2",
    },
    # ─── DeepSeek: Current ────────────────────────────────────────────
    "deepseek-reasoner": {
        "id": "deepseek-reasoner",
        "display_name": "DeepSeek Reasoner",
        "provider": "DeepSeek",
        "context_window": 128_000,
        "max_output_tokens": 64_000,
        "vision": False,
        "reasoning": True,
        "pricing_input": 0.28,
        "pricing_output": 0.42,
        "knowledge_cutoff": "2025-09",
        "release_date": "2025-09",
        "status": "current",
        "notes": "DeepSeek-V3.2 Thinking Mode, chain-of-thought reasoning",
    },
    "deepseek-chat": {
        "id": "deepseek-chat",
        "display_name": "DeepSeek Chat",
        "provider": "DeepSeek",
        "context_window": 128_000,
        "max_output_tokens": 8_000,
        "vision": False,
        "reasoning": False,
        "pricing_input": 0.28,
        "pricing_output": 0.42,
        "knowledge_cutoff": "2025-09",
        "release_date": "2025-09",
        "status": "current",
        "notes": "DeepSeek-V3.2 Non-thinking Mode, open-weight MoE",
    },
    # ─── DeepSeek: Legacy ────────────────────────────────────────────
    "deepseek-v3": {
        "id": "deepseek-v3",
        "display_name": "DeepSeek V3",
        "provider": "DeepSeek",
        "context_window": 128_000,
        "max_output_tokens": 16_384,
        "vision": False,
        "reasoning": False,
        "pricing_input": 0.27,
        "pricing_output": 1.10,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-01",
        "status": "deprecated",
        "notes": "Merged into deepseek-chat (V3.2), no longer a separate endpoint",
    },
}
