"""Curated static registry of current AI models across major providers."""

MODELS = {
    # ─── OpenAI: Current ───────────────────────────────────────────────
    "gpt-5.2": {
        "id": "gpt-5.2",
        "display_name": "GPT-5.2",
        "provider": "OpenAI",
        "context_window": 256_000,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 3.00,
        "pricing_output": 12.00,
        "knowledge_cutoff": "2025-12",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Latest flagship GPT model",
    },
    "gpt-5": {
        "id": "gpt-5",
        "display_name": "GPT-5",
        "provider": "OpenAI",
        "context_window": 256_000,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 2.50,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2025-06",
        "release_date": "2025-08",
        "status": "current",
        "notes": "",
    },
    "gpt-5-mini": {
        "id": "gpt-5-mini",
        "display_name": "GPT-5 Mini",
        "provider": "OpenAI",
        "context_window": 256_000,
        "max_output_tokens": 16_384,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.40,
        "pricing_output": 1.60,
        "knowledge_cutoff": "2025-06",
        "release_date": "2025-09",
        "status": "current",
        "notes": "Cost-efficient GPT-5 variant",
    },
    "gpt-4.1": {
        "id": "gpt-4.1",
        "display_name": "GPT-4.1",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 2.00,
        "pricing_output": 8.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "1M context window, strong coding model",
    },
    "gpt-4.1-mini": {
        "id": "gpt-4.1-mini",
        "display_name": "GPT-4.1 Mini",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.40,
        "pricing_output": 1.60,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "1M context, cost-efficient",
    },
    "gpt-4.1-nano": {
        "id": "gpt-4.1-nano",
        "display_name": "GPT-4.1 Nano",
        "provider": "OpenAI",
        "context_window": 1_047_576,
        "max_output_tokens": 32_768,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Fastest and cheapest GPT-4.1 variant",
    },
    "o3": {
        "id": "o3",
        "display_name": "o3",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 10.00,
        "pricing_output": 40.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Flagship reasoning model",
    },
    "o4-mini": {
        "id": "o4-mini",
        "display_name": "o4-mini",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.10,
        "pricing_output": 4.40,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-04",
        "status": "current",
        "notes": "Cost-efficient reasoning model",
    },
    "o3-mini": {
        "id": "o3-mini",
        "display_name": "o3-mini",
        "provider": "OpenAI",
        "context_window": 200_000,
        "max_output_tokens": 100_000,
        "vision": False,
        "reasoning": True,
        "pricing_input": 1.10,
        "pricing_output": 4.40,
        "knowledge_cutoff": "2025-01",
        "release_date": "2025-01",
        "status": "current",
        "notes": "Predecessor to o4-mini, still available",
    },
    # ─── OpenAI: Legacy/Deprecated ─────────────────────────────────────
    "gpt-4o": {
        "id": "gpt-4o",
        "display_name": "GPT-4o",
        "provider": "OpenAI",
        "context_window": 128_000,
        "max_output_tokens": 16_384,
        "vision": True,
        "reasoning": False,
        "pricing_input": 2.50,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2024-10",
        "release_date": "2024-05",
        "status": "legacy",
        "notes": "Superseded by GPT-4.1 and GPT-5 series",
    },
    "gpt-4o-mini": {
        "id": "gpt-4o-mini",
        "display_name": "GPT-4o Mini",
        "provider": "OpenAI",
        "context_window": 128_000,
        "max_output_tokens": 16_384,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.15,
        "pricing_output": 0.60,
        "knowledge_cutoff": "2024-10",
        "release_date": "2024-07",
        "status": "deprecated",
        "notes": "Superseded by GPT-4.1 Mini/Nano",
    },
    # ─── Anthropic: Current ────────────────────────────────────────────
    "claude-opus-4-6": {
        "id": "claude-opus-4-6",
        "display_name": "Claude Opus 4.6",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 32_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 15.00,
        "pricing_output": 75.00,
        "knowledge_cutoff": "2025-05",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Most capable Anthropic model, extended thinking",
    },
    "claude-sonnet-4-5-20250929": {
        "id": "claude-sonnet-4-5-20250929",
        "display_name": "Claude Sonnet 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 16_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2025-04",
        "release_date": "2025-09",
        "status": "current",
        "notes": "Balanced performance and cost, extended thinking",
    },
    "claude-haiku-4-5-20251001": {
        "id": "claude-haiku-4-5-20251001",
        "display_name": "Claude Haiku 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.80,
        "pricing_output": 4.00,
        "knowledge_cutoff": "2025-04",
        "release_date": "2025-10",
        "status": "current",
        "notes": "Fast and cost-efficient",
    },
    # ─── Anthropic: Legacy/Deprecated ──────────────────────────────────
    "claude-opus-4-5": {
        "id": "claude-opus-4-5",
        "display_name": "Claude Opus 4.5",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 32_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 15.00,
        "pricing_output": 75.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-06",
        "status": "legacy",
        "notes": "Superseded by Claude Opus 4.6",
    },
    "claude-sonnet-4-0": {
        "id": "claude-sonnet-4-0",
        "display_name": "Claude Sonnet 4.0",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 16_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-06",
        "status": "legacy",
        "notes": "Superseded by Claude Sonnet 4.5",
    },
    "claude-3-7-sonnet": {
        "id": "claude-3-7-sonnet",
        "display_name": "Claude 3.7 Sonnet",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": True,
        "pricing_input": 3.00,
        "pricing_output": 15.00,
        "knowledge_cutoff": "2025-02",
        "release_date": "2025-02",
        "status": "deprecated",
        "notes": "Superseded by Claude Sonnet 4.x series",
    },
    "claude-opus-4-0": {
        "id": "claude-opus-4-0",
        "display_name": "Claude Opus 4.0",
        "provider": "Anthropic",
        "context_window": 200_000,
        "max_output_tokens": 32_000,
        "vision": True,
        "reasoning": True,
        "pricing_input": 15.00,
        "pricing_output": 75.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-05",
        "status": "legacy",
        "notes": "Superseded by Claude Opus 4.5/4.6",
    },
    # ─── Google: Current ───────────────────────────────────────────────
    "gemini-3-pro-preview": {
        "id": "gemini-3-pro-preview",
        "display_name": "Gemini 3 Pro (Preview)",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.25,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2025-09",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Latest Gemini flagship, 1M context, preview",
    },
    "gemini-3-flash-preview": {
        "id": "gemini-3-flash-preview",
        "display_name": "Gemini 3 Flash (Preview)",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 0.15,
        "pricing_output": 0.60,
        "knowledge_cutoff": "2025-09",
        "release_date": "2026-01",
        "status": "current",
        "notes": "Fast and cheap Gemini 3 variant, preview",
    },
    "gemini-2.5-pro": {
        "id": "gemini-2.5-pro",
        "display_name": "Gemini 2.5 Pro",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 1.25,
        "pricing_output": 10.00,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-03",
        "status": "current",
        "notes": "Thinking model, 1M context",
    },
    "gemini-2.5-flash": {
        "id": "gemini-2.5-flash",
        "display_name": "Gemini 2.5 Flash",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": True,
        "pricing_input": 0.15,
        "pricing_output": 0.60,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-05",
        "status": "current",
        "notes": "Fast and cost-efficient with thinking",
    },
    "gemini-2.5-flash-lite": {
        "id": "gemini-2.5-flash-lite",
        "display_name": "Gemini 2.5 Flash Lite",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 65_536,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.075,
        "pricing_output": 0.30,
        "knowledge_cutoff": "2025-03",
        "release_date": "2025-06",
        "status": "current",
        "notes": "Cheapest Gemini option, no thinking mode",
    },
    # ─── Google: Legacy/Deprecated ─────────────────────────────────────
    "gemini-2.0-flash": {
        "id": "gemini-2.0-flash",
        "display_name": "Gemini 2.0 Flash",
        "provider": "Google",
        "context_window": 1_048_576,
        "max_output_tokens": 8_192,
        "vision": True,
        "reasoning": False,
        "pricing_input": 0.10,
        "pricing_output": 0.40,
        "knowledge_cutoff": "2024-08",
        "release_date": "2025-02",
        "status": "deprecated",
        "notes": "Retiring March 2026, use Gemini 2.5 Flash instead",
    },
}
