package models

// Models contains all AI model entries in the registry.
// Data verified against official docs as of February 2026.
var Models = map[string]Model{
	// ─── OpenAI: Current ───────────────────────────────────────────────
	"gpt-5.2": {
		ID:              "gpt-5.2",
		DisplayName:     "GPT-5.2",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.75,
		PricingOutput:   14.00,
		KnowledgeCutoff: "2025-08",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Latest flagship GPT model with thinking, 400K context",
	},
	"gpt-5.2-codex": {
		ID:              "gpt-5.2-codex",
		DisplayName:     "GPT-5.2 Codex",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.75,
		PricingOutput:   14.00,
		KnowledgeCutoff: "2025-08",
		ReleaseDate:     "2026-01",
		Status:          "current",
		Notes:           "Optimized for agentic coding, strong long-horizon task completion",
	},
	"gpt-5.2-pro": {
		ID:              "gpt-5.2-pro",
		DisplayName:     "GPT-5.2 Pro",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    21.00,
		PricingOutput:   168.00,
		KnowledgeCutoff: "2025-08",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Pro variant with extended reasoning, Responses API only",
	},
	"gpt-5.1": {
		ID:              "gpt-5.1",
		DisplayName:     "GPT-5.1",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.25,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2024-09",
		ReleaseDate:     "2025-11",
		Status:          "current",
		Notes:           "Flagship for coding and agentic tasks",
	},
	"gpt-5": {
		ID:              "gpt-5",
		DisplayName:     "GPT-5",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.25,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2025-08",
		Status:          "current",
		Notes:           "400K context, flagship with configurable reasoning",
	},
	"gpt-5-mini": {
		ID:              "gpt-5-mini",
		DisplayName:     "GPT-5 Mini",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.25,
		PricingOutput:   2.00,
		KnowledgeCutoff: "2024-05",
		ReleaseDate:     "2025-09",
		Status:          "current",
		Notes:           "Cost-efficient GPT-5 variant, 400K context, reasoning support",
	},
	"gpt-5-nano": {
		ID:              "gpt-5-nano",
		DisplayName:     "GPT-5 Nano",
		Provider:        "OpenAI",
		ContextWindow:   400_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.05,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2024-05",
		ReleaseDate:     "2025-08",
		Status:          "current",
		Notes:           "Fastest and cheapest GPT-5 variant, great for summarization/classification",
	},
	"gpt-4.1-mini": {
		ID:              "gpt-4.1-mini",
		DisplayName:     "GPT-4.1 Mini",
		Provider:        "OpenAI",
		ContextWindow:   1_047_576,
		MaxOutputTokens: 32_768,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.40,
		PricingOutput:   1.60,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "1M context, cost-efficient",
	},
	"gpt-4.1-nano": {
		ID:              "gpt-4.1-nano",
		DisplayName:     "GPT-4.1 Nano",
		Provider:        "OpenAI",
		ContextWindow:   1_047_576,
		MaxOutputTokens: 32_768,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.10,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Fastest and cheapest GPT-4.1 variant",
	},
	"o3": {
		ID:              "o3",
		DisplayName:     "o3",
		Provider:        "OpenAI",
		ContextWindow:   200_000,
		MaxOutputTokens: 100_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    2.00,
		PricingOutput:   8.00,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Flagship reasoning model, strong at math/science/coding",
	},
	"o3-pro": {
		ID:              "o3-pro",
		DisplayName:     "o3 Pro",
		Provider:        "OpenAI",
		ContextWindow:   200_000,
		MaxOutputTokens: 100_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    20.00,
		PricingOutput:   80.00,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-06",
		Status:          "current",
		Notes:           "Extended thinking version of o3, available via Responses API only",
	},
	"o4-mini": {
		ID:              "o4-mini",
		DisplayName:     "o4-mini",
		Provider:        "OpenAI",
		ContextWindow:   200_000,
		MaxOutputTokens: 100_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.10,
		PricingOutput:   4.40,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Cost-efficient reasoning model",
	},
	"o3-mini": {
		ID:              "o3-mini",
		DisplayName:     "o3-mini",
		Provider:        "OpenAI",
		ContextWindow:   200_000,
		MaxOutputTokens: 100_000,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    1.10,
		PricingOutput:   4.40,
		KnowledgeCutoff: "2023-10",
		ReleaseDate:     "2025-01",
		Status:          "legacy",
		Notes:           "Predecessor to o4-mini, superseded by o4-mini",
	},
	// ─── OpenAI: Legacy/Deprecated ─────────────────────────────────────
	"gpt-4.1": {
		ID:              "gpt-4.1",
		DisplayName:     "GPT-4.1",
		Provider:        "OpenAI",
		ContextWindow:   1_047_576,
		MaxOutputTokens: 32_768,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    2.00,
		PricingOutput:   8.00,
		KnowledgeCutoff: "2024-06",
		ReleaseDate:     "2025-04",
		Status:          "legacy",
		Notes:           "1M context window, strong coding. Retiring from ChatGPT Feb 13, 2026. Superseded by GPT-5 series",
	},
	"gpt-4o": {
		ID:              "gpt-4o",
		DisplayName:     "GPT-4o",
		Provider:        "OpenAI",
		ContextWindow:   128_000,
		MaxOutputTokens: 16_384,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    2.50,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2023-10",
		ReleaseDate:     "2024-05",
		Status:          "deprecated",
		Notes:           "Retiring Feb 13, 2026. Superseded by GPT-5 series",
	},
	"gpt-4o-mini": {
		ID:              "gpt-4o-mini",
		DisplayName:     "GPT-4o Mini",
		Provider:        "OpenAI",
		ContextWindow:   128_000,
		MaxOutputTokens: 16_384,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.15,
		PricingOutput:   0.60,
		KnowledgeCutoff: "2023-10",
		ReleaseDate:     "2024-07",
		Status:          "deprecated",
		Notes:           "Superseded by GPT-4.1 Mini/Nano",
	},
	// ─── Anthropic: Current ────────────────────────────────────────────
	"claude-opus-4-6": {
		ID:              "claude-opus-4-6",
		DisplayName:     "Claude Opus 4.6",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 128_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    5.00,
		PricingOutput:   25.00,
		KnowledgeCutoff: "2025-05",
		ReleaseDate:     "2026-02",
		Status:          "current",
		Notes:           "Most capable Anthropic model, extended thinking, adaptive thinking. 1M token context window available in beta (requires context-1m-2025-08-07 header, tier 4+ orgs). Premium pricing >200K: $10/$37.50 per 1M tokens.",
	},
	"claude-sonnet-4-5-20250929": {
		ID:              "claude-sonnet-4-5-20250929",
		DisplayName:     "Claude Sonnet 4.5",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 64_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-09",
		Status:          "current",
		Notes:           "Best speed/intelligence balance, extended thinking. Alias: claude-sonnet-4-5",
	},
	"claude-haiku-4-5-20251001": {
		ID:              "claude-haiku-4-5-20251001",
		DisplayName:     "Claude Haiku 4.5",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 64_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.00,
		PricingOutput:   5.00,
		KnowledgeCutoff: "2025-02",
		ReleaseDate:     "2025-10",
		Status:          "current",
		Notes:           "Fastest Anthropic model, extended thinking. Alias: claude-haiku-4-5",
	},
	// ─── Anthropic: Legacy/Deprecated ──────────────────────────────────
	"claude-opus-4-5": {
		ID:              "claude-opus-4-5",
		DisplayName:     "Claude Opus 4.5",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 64_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    5.00,
		PricingOutput:   25.00,
		KnowledgeCutoff: "2025-05",
		ReleaseDate:     "2025-11",
		Status:          "legacy",
		Notes:           "Superseded by Claude Opus 4.6. Full ID: claude-opus-4-5-20251101",
	},
	"claude-opus-4-1": {
		ID:              "claude-opus-4-1",
		DisplayName:     "Claude Opus 4.1",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 32_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    15.00,
		PricingOutput:   75.00,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-08",
		Status:          "legacy",
		Notes:           "Superseded by Claude Opus 4.5/4.6. Full ID: claude-opus-4-1-20250805",
	},
	"claude-sonnet-4-0": {
		ID:              "claude-sonnet-4-0",
		DisplayName:     "Claude Sonnet 4.0",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 64_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-05",
		Status:          "legacy",
		Notes:           "Superseded by Claude Sonnet 4.5. Full ID: claude-sonnet-4-20250514",
	},
	"claude-3-7-sonnet-20250219": {
		ID:              "claude-3-7-sonnet-20250219",
		DisplayName:     "Claude 3.7 Sonnet",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 64_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2025-02",
		Status:          "deprecated",
		Notes:           "Superseded by Claude Sonnet 4.x. Alias: claude-3-7-sonnet-latest",
	},
	"claude-opus-4-0": {
		ID:              "claude-opus-4-0",
		DisplayName:     "Claude Opus 4.0",
		Provider:        "Anthropic",
		ContextWindow:   200_000,
		MaxOutputTokens: 32_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    15.00,
		PricingOutput:   75.00,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-05",
		Status:          "legacy",
		Notes:           "Superseded by Claude Opus 4.5/4.6. Full ID: claude-opus-4-20250514",
	},
	// ─── Google: Current ───────────────────────────────────────────────
	"gemini-3-pro-preview": {
		ID:              "gemini-3-pro-preview",
		DisplayName:     "Gemini 3 Pro (Preview)",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    2.00,
		PricingOutput:   12.00,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-11",
		Status:          "current",
		Notes:           "Latest Gemini flagship, 1M context, preview",
	},
	"gemini-3-flash-preview": {
		ID:              "gemini-3-flash-preview",
		DisplayName:     "Gemini 3 Flash (Preview)",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.50,
		PricingOutput:   3.00,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Fast Gemini 3 variant, preview",
	},
	"gemini-2.5-pro": {
		ID:              "gemini-2.5-pro",
		DisplayName:     "Gemini 2.5 Pro",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.25,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-03",
		Status:          "current",
		Notes:           "Thinking model, 1M context",
	},
	"gemini-2.5-flash": {
		ID:              "gemini-2.5-flash",
		DisplayName:     "Gemini 2.5 Flash",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.30,
		PricingOutput:   2.50,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-05",
		Status:          "current",
		Notes:           "Fast and cost-efficient with thinking",
	},
	"gemini-2.5-flash-lite": {
		ID:              "gemini-2.5-flash-lite",
		DisplayName:     "Gemini 2.5 Flash Lite",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.10,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-06",
		Status:          "current",
		Notes:           "Cheapest Gemini option, no thinking mode",
	},
	// ─── Google: Legacy/Deprecated ─────────────────────────────────────
	"gemini-2.0-flash": {
		ID:              "gemini-2.0-flash",
		DisplayName:     "Gemini 2.0 Flash",
		Provider:        "Google",
		ContextWindow:   1_048_576,
		MaxOutputTokens: 8_192,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.10,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2024-08",
		ReleaseDate:     "2025-02",
		Status:          "deprecated",
		Notes:           "Retiring March 2026, use Gemini 2.5 Flash instead",
	},
	// ─── xAI: Current ──────────────────────────────────────────────────
	"grok-4": {
		ID:              "grok-4",
		DisplayName:     "Grok 4",
		Provider:        "xAI",
		ContextWindow:   256_000,
		MaxOutputTokens: 131_072,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-07",
		Status:          "current",
		Notes:           "xAI flagship reasoning model",
	},
	"grok-4.1-fast": {
		ID:              "grok-4.1-fast",
		DisplayName:     "Grok 4.1 Fast",
		Provider:        "xAI",
		ContextWindow:   2_000_000,
		MaxOutputTokens: 8_192,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.20,
		PricingOutput:   0.50,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-11",
		Status:          "current",
		Notes:           "2M context, fast tool-calling model, low hallucination",
	},
	"grok-4-fast": {
		ID:              "grok-4-fast",
		DisplayName:     "Grok 4 Fast",
		Provider:        "xAI",
		ContextWindow:   2_000_000,
		MaxOutputTokens: 30_000,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.20,
		PricingOutput:   0.50,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-09",
		Status:          "current",
		Notes:           "2M context, reasoning and non-reasoning modes, 40% fewer thinking tokens vs Grok 4",
	},
	"grok-code-fast-1": {
		ID:              "grok-code-fast-1",
		DisplayName:     "Grok Code Fast 1",
		Provider:        "xAI",
		ContextWindow:   256_000,
		MaxOutputTokens: 65_536,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    0.20,
		PricingOutput:   1.50,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-08",
		Status:          "current",
		Notes:           "Specialized agentic coding model, SWE-Bench 70.8%",
	},
	// ─── xAI: Legacy ───────────────────────────────────────────────────
	"grok-3": {
		ID:              "grok-3",
		DisplayName:     "Grok 3",
		Provider:        "xAI",
		ContextWindow:   131_072,
		MaxOutputTokens: 131_072,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-02",
		Status:          "legacy",
		Notes:           "Superseded by Grok 4 series",
	},
	"grok-3-mini": {
		ID:              "grok-3-mini",
		DisplayName:     "Grok 3 Mini",
		Provider:        "xAI",
		ContextWindow:   131_072,
		MaxOutputTokens: 131_072,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    0.30,
		PricingOutput:   0.50,
		KnowledgeCutoff: "2024-11",
		ReleaseDate:     "2025-02",
		Status:          "legacy",
		Notes:           "Compact reasoning model, superseded by Grok 4.1 Fast",
	},
	// ─── Meta: Current ─────────────────────────────────────────────────
	"llama-4-maverick": {
		ID:              "llama-4-maverick",
		DisplayName:     "Llama 4 Maverick",
		Provider:        "Meta",
		ContextWindow:   512_000,
		MaxOutputTokens: 32_768,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.20,
		PricingOutput:   0.60,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Open-weight MoE, no direct Meta API, access via Together/Fireworks/Groq",
	},
	"llama-4-scout": {
		ID:              "llama-4-scout",
		DisplayName:     "Llama 4 Scout",
		Provider:        "Meta",
		ContextWindow:   10_000_000,
		MaxOutputTokens: 32_768,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.15,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Open-weight, 10M context, no direct Meta API, access via third-party providers",
	},
	// ─── Meta: Legacy ──────────────────────────────────────────────────
	"llama-3.3-70b": {
		ID:              "llama-3.3-70b",
		DisplayName:     "Llama 3.3 70B",
		Provider:        "Meta",
		ContextWindow:   128_000,
		MaxOutputTokens: 4_096,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.10,
		PricingOutput:   0.30,
		KnowledgeCutoff: "2024-12",
		ReleaseDate:     "2024-12",
		Status:          "legacy",
		Notes:           "Superseded by Llama 4 series, access via third-party providers",
	},
	// ─── Mistral: Current ──────────────────────────────────────────────
	"mistral-large-2512": {
		ID:              "mistral-large-2512",
		DisplayName:     "Mistral Large 3",
		Provider:        "Mistral",
		ContextWindow:   256_000,
		MaxOutputTokens: 8_192,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.50,
		PricingOutput:   1.50,
		KnowledgeCutoff: "2025-11",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "MoE 675B flagship, strong multilingual, Apache 2.0",
	},
	"mistral-small-2506": {
		ID:              "mistral-small-2506",
		DisplayName:     "Mistral Small 3.2",
		Provider:        "Mistral",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_192,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.10,
		PricingOutput:   0.30,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-06",
		Status:          "current",
		Notes:           "Fast and cost-efficient, open-weight",
	},
	"devstral-2512": {
		ID:              "devstral-2512",
		DisplayName:     "Devstral 2",
		Provider:        "Mistral",
		ContextWindow:   256_000,
		MaxOutputTokens: 8_192,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.40,
		PricingOutput:   2.00,
		KnowledgeCutoff: "2025-11",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Specialized coding agent model, open-weight",
	},
	"mistral-medium-2505": {
		ID:              "mistral-medium-2505",
		DisplayName:     "Mistral Medium 3",
		Provider:        "Mistral",
		ContextWindow:   131_072,
		MaxOutputTokens: 8_192,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.40,
		PricingOutput:   2.00,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-05",
		Status:          "current",
		Notes:           "Mid-tier Mistral model, good vision support, strong multilingual",
	},
	"devstral-small-2512": {
		ID:              "devstral-small-2512",
		DisplayName:     "Devstral Small 2",
		Provider:        "Mistral",
		ContextWindow:   256_000,
		MaxOutputTokens: 8_192,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.40,
		PricingOutput:   2.00,
		KnowledgeCutoff: "2025-11",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "24B coding model, runs on consumer GPUs, Apache 2.0, companion to Devstral 2",
	},
	// ─── Mistral: Legacy ───────────────────────────────────────────────
	"codestral-2508": {
		ID:              "codestral-2508",
		DisplayName:     "Codestral",
		Provider:        "Mistral",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_192,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.30,
		PricingOutput:   0.90,
		KnowledgeCutoff: "2025-03",
		ReleaseDate:     "2025-08",
		Status:          "legacy",
		Notes:           "Superseded by Devstral 2",
	},
	// ─── DeepSeek: Current ─────────────────────────────────────────────
	"deepseek-reasoner": {
		ID:              "deepseek-reasoner",
		DisplayName:     "DeepSeek Reasoner",
		Provider:        "DeepSeek",
		ContextWindow:   128_000,
		MaxOutputTokens: 64_000,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    0.28,
		PricingOutput:   0.42,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-09",
		Status:          "current",
		Notes:           "DeepSeek-V3.2 Thinking Mode, chain-of-thought reasoning",
	},
	"deepseek-chat": {
		ID:              "deepseek-chat",
		DisplayName:     "DeepSeek Chat",
		Provider:        "DeepSeek",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.28,
		PricingOutput:   0.42,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-09",
		Status:          "current",
		Notes:           "DeepSeek-V3.2 Non-thinking Mode, open-weight MoE",
	},
	"deepseek-r1": {
		ID:              "deepseek-r1",
		DisplayName:     "DeepSeek R1",
		Provider:        "DeepSeek",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    0.55,
		PricingOutput:   2.19,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-01",
		Status:          "current",
		Notes:           "Open-source reasoning model, o1-level performance at fraction of cost, widely deployed",
	},
	// ─── DeepSeek: Legacy ──────────────────────────────────────────────
	"deepseek-v3": {
		ID:              "deepseek-v3",
		DisplayName:     "DeepSeek V3",
		Provider:        "DeepSeek",
		ContextWindow:   128_000,
		MaxOutputTokens: 16_384,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.27,
		PricingOutput:   1.10,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-01",
		Status:          "deprecated",
		Notes:           "Merged into deepseek-chat (V3.2), no longer a separate endpoint",
	},
	// ─── Amazon: Current ───────────────────────────────────────────────
	"amazon-nova-micro": {
		ID:              "amazon-nova-micro",
		DisplayName:     "Amazon Nova Micro",
		Provider:        "Amazon",
		ContextWindow:   128_000,
		MaxOutputTokens: 5_000,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.035,
		PricingOutput:   0.14,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2024-12",
		Status:          "current",
		Notes:           "Text-only, lowest latency Nova model, via Amazon Bedrock",
	},
	"amazon-nova-lite": {
		ID:              "amazon-nova-lite",
		DisplayName:     "Amazon Nova Lite",
		Provider:        "Amazon",
		ContextWindow:   300_000,
		MaxOutputTokens: 5_000,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.06,
		PricingOutput:   0.24,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2024-12",
		Status:          "current",
		Notes:           "Multimodal (text, image, video), fast and low-cost, via Amazon Bedrock",
	},
	"amazon-nova-pro": {
		ID:              "amazon-nova-pro",
		DisplayName:     "Amazon Nova Pro",
		Provider:        "Amazon",
		ContextWindow:   300_000,
		MaxOutputTokens: 5_000,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    0.80,
		PricingOutput:   3.20,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2024-12",
		Status:          "current",
		Notes:           "Multimodal, best balance of accuracy/speed/cost, agentic workflows, via Amazon Bedrock",
	},
	"amazon-nova-premier": {
		ID:              "amazon-nova-premier",
		DisplayName:     "Amazon Nova Premier",
		Provider:        "Amazon",
		ContextWindow:   1_000_000,
		MaxOutputTokens: 5_000,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    2.50,
		PricingOutput:   12.50,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2025-04",
		Status:          "current",
		Notes:           "Most capable Nova 1.0, 1M context, teacher for distillation, via Amazon Bedrock",
	},
	"amazon-nova-2-lite": {
		ID:              "amazon-nova-2-lite",
		DisplayName:     "Amazon Nova 2 Lite",
		Provider:        "Amazon",
		ContextWindow:   1_000_000,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    1.25,
		PricingOutput:   2.50,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Fast reasoning model, extended thinking with budget controls, 1M context, via Amazon Bedrock",
	},
	"amazon-nova-2-pro": {
		ID:              "amazon-nova-2-pro",
		DisplayName:     "Amazon Nova 2 Pro (Preview)",
		Provider:        "Amazon",
		ContextWindow:   1_000_000,
		MaxOutputTokens: 65_536,
		Vision:          true,
		Reasoning:       true,
		PricingInput:    0.30,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2025-09",
		ReleaseDate:     "2025-12",
		Status:          "current",
		Notes:           "Most capable Nova 2, complex agentic tasks, 1M context, preview, via Amazon Bedrock",
	},
	// ─── Cohere: Current ───────────────────────────────────────────────
	"command-a-03-2025": {
		ID:              "command-a-03-2025",
		DisplayName:     "Command A",
		Provider:        "Cohere",
		ContextWindow:   256_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    2.50,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2025-01",
		ReleaseDate:     "2025-03",
		Status:          "current",
		Notes:           "Cohere flagship, 111B params, excels at RAG/tool use/agents, runs on 2 GPUs",
	},
	"command-a-reasoning-08-2025": {
		ID:              "command-a-reasoning-08-2025",
		DisplayName:     "Command A Reasoning",
		Provider:        "Cohere",
		ContextWindow:   256_000,
		MaxOutputTokens: 32_000,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    2.50,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2025-06",
		ReleaseDate:     "2025-08",
		Status:          "current",
		Notes:           "Reasoning variant of Command A, extended output, enterprise agentic workflows",
	},
	"command-a-vision-07-2025": {
		ID:              "command-a-vision-07-2025",
		DisplayName:     "Command A Vision",
		Provider:        "Cohere",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_000,
		Vision:          true,
		Reasoning:       false,
		PricingInput:    2.50,
		PricingOutput:   10.00,
		KnowledgeCutoff: "2025-05",
		ReleaseDate:     "2025-07",
		Status:          "current",
		Notes:           "Multimodal Command A, 112B params, up to 20 images per request, open weights",
	},
	"command-r7b-12-2024": {
		ID:              "command-r7b-12-2024",
		DisplayName:     "Command R7B",
		Provider:        "Cohere",
		ContextWindow:   128_000,
		MaxOutputTokens: 4_096,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.0375,
		PricingOutput:   0.15,
		KnowledgeCutoff: "2024-10",
		ReleaseDate:     "2024-12",
		Status:          "current",
		Notes:           "Smallest R-series, 7B params, fast tool use, 23 languages, runs on consumer GPUs",
	},
	// ─── Perplexity: Current ───────────────────────────────────────────
	"sonar": {
		ID:              "sonar",
		DisplayName:     "Sonar",
		Provider:        "Perplexity",
		ContextWindow:   127_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    1.00,
		PricingOutput:   1.00,
		KnowledgeCutoff: "2025-02",
		ReleaseDate:     "2025-02",
		Status:          "current",
		Notes:           "Search-augmented LLM, returns answers with citations, cost-effective",
	},
	"sonar-pro": {
		ID:              "sonar-pro",
		DisplayName:     "Sonar Pro",
		Provider:        "Perplexity",
		ContextWindow:   200_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    3.00,
		PricingOutput:   15.00,
		KnowledgeCutoff: "2025-02",
		ReleaseDate:     "2025-02",
		Status:          "current",
		Notes:           "Advanced search-augmented LLM, 2x citations vs Sonar, 200K context, multi-step queries",
	},
	"sonar-reasoning-pro": {
		ID:              "sonar-reasoning-pro",
		DisplayName:     "Sonar Reasoning Pro",
		Provider:        "Perplexity",
		ContextWindow:   128_000,
		MaxOutputTokens: 8_000,
		Vision:          false,
		Reasoning:       true,
		PricingInput:    2.00,
		PricingOutput:   8.00,
		KnowledgeCutoff: "2025-02",
		ReleaseDate:     "2025-03",
		Status:          "current",
		Notes:           "Reasoning model powered by DeepSeek R1 with CoT, search-augmented",
	},
	// ─── AI21: Current ─────────────────────────────────────────────────
	"jamba-large-1.7": {
		ID:              "jamba-large-1.7",
		DisplayName:     "Jamba Large 1.7",
		Provider:        "AI21",
		ContextWindow:   256_000,
		MaxOutputTokens: 4_096,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    2.00,
		PricingOutput:   8.00,
		KnowledgeCutoff: "2025-06",
		ReleaseDate:     "2025-08",
		Status:          "current",
		Notes:           "SSM-Transformer hybrid, 256K context, enterprise-focused, available via AI21 API and Bedrock",
	},
	"jamba-mini-1.7": {
		ID:              "jamba-mini-1.7",
		DisplayName:     "Jamba Mini 1.7",
		Provider:        "AI21",
		ContextWindow:   256_000,
		MaxOutputTokens: 4_096,
		Vision:          false,
		Reasoning:       false,
		PricingInput:    0.20,
		PricingOutput:   0.40,
		KnowledgeCutoff: "2025-06",
		ReleaseDate:     "2025-07",
		Status:          "current",
		Notes:           "Compact SSM-Transformer hybrid, 12B active params, 256K context, cost-efficient",
	},
}
